public enum Name
{
  PENCIL_TOOL, PAINT_TOOL, LINE_TOOL, CURVE_TOOL, ELLIPSE_TOOL, RECT_TOOL, POLYGON_TOOL, TEXT_TOOL,
  UNGROUP_TOOL, GROUP_TOOL, BUCKET_TOOL, ZOOM_TOOL, UNDO_TOOL, CURSOR_TOOL, PAN_TOOL, SAVE_TOOL,
  WHITE_COLOR, BLACK_COLOR, RED_COLOR, GREEN_COLOR, BLUE_COLOR, YELLOW_COLOR, CYAN_COLOR, MAGENTA_COLOR
}